### ISSUE TITLE
Runserver error.

### ISSUE THREAD

**Issue by Ghukek** [duanzhiihao/youtubeAnalyze#4]
My terminal output is as follows:

>nathan@[computername] ~/Documents/EC601/Youtube/youtubeAnalyze/zhduan $ python manage.py runserver 0:80
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f0eec4e46a8>
Traceback (most recent call last):
  File "/home/nathan/anaconda3/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/nathan/anaconda3/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/nathan/anaconda3/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/nathan/anaconda3/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/nathan/anaconda3/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/nathan/anaconda3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nathan/anaconda3/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/home/nathan/anaconda3/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/nathan/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'social_django'

I installed Django using, `pip install Django` according to the instructions in the ReadMe.

**Comment by Ghukek** [comment]
I got it working by running `pip install python-social-auth[django]` but then I get,

> nathan@[computername] ~/Documents/EC601/Youtube/youtubeAnalyze/zhduan $ pytn manage.py runserver 0:80
Performing system checks...
System check identified no issues (0 silenced).
November 03, 2018 - 20:39:19
Django version 2.1.3, using settings 'zhduan.settings'
Starting development server at http://0:80/
Quit the server with CONTROL-C.
Error: You don't have permission to access that port.

However, I was able to solve that issue by removing the 0:80 port, which allowed the server to start on the default port of 8000. Successful ouptut is,

>nathan@[computername] ~/Documents/EC601/Youtube/youtubeAnalyze/zhduan $ python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2018 - 20:42:14
Django version 2.1.3, using settings 'zhduan.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

**Comment by duanzhiihao** [comment]
Thank you very much, I will change my readme

**Comment by Ghukek** [comment]
Running on port 8000 breaks Google Oauth login, as it is not the proper redirect URL.

**Comment by duanzhiihao** [comment]
> Running on port 8000 breaks Google Oauth login, as it is not the proper redirect URL.

Yep, simply running localhost can't use Google OAuth2.

If you want use that function, you should customize it.
1. Go to [Google Cloud Platform - APIs and Services - Credentials](https://console.cloud.google.com/apis/credentials)
2. Click ```Create credentials``` - ```OAuth client ID``` - ```Web Application```
3. Fill the ```Authorized redirect URIs``` using your domain name ( I don't know whether using your localhost IP adress is possible, I've never tried that. Howerver, Google says it 'Cannot be a public IP address'. So maybe Login with Google is imposiible in localhost ), like
```
http://www.zhduan.com/youtube/oathcomplete/google-oauth2/
and
http://zhduan.com/youtube/oathcomplete/google-oauth2/
```
4. Finishing creating credentials, then you will get your ```Client ID``` and ```Client secret```
5. At [Google Cloud Platform - APIs and Services - OAuth consent screen](https://console.cloud.google.com/apis/credentials/consent), fill the information about your website
5. Replace the ```SOCIAL_AUTH_GOOGLE_OAUTH2_KEY``` and ```SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET``` in ```line 145 and 146``` in ```/zhduan/zhduan/settings.py``` with your ```Client ID``` and ```Client secret```, instead of mine.
6. Then you are done, try to login with Google account on your website
